// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTjRCgSBD2AdmEsvUmSyKJ8SOmKG2ztqI',
    appId: '1:845713431117:web:f1064f21e4388e61d49a04',
    messagingSenderId: '845713431117',
    projectId: 'fp-ppb-recipe',
    authDomain: 'fp-ppb-recipe.firebaseapp.com',
    storageBucket: 'fp-ppb-recipe.firebasestorage.app',
    measurementId: 'G-BR92S0P43Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM34M-ZVMnF-clcKAca3qrK3yH0ZmUYv0',
    appId: '1:845713431117:android:50a569ab79128bd2d49a04',
    messagingSenderId: '845713431117',
    projectId: 'fp-ppb-recipe',
    storageBucket: 'fp-ppb-recipe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATkmYhJbKldDd93-CctvMDVsr0K26SkjM',
    appId: '1:845713431117:ios:defb6f8fd78883fed49a04',
    messagingSenderId: '845713431117',
    projectId: 'fp-ppb-recipe',
    storageBucket: 'fp-ppb-recipe.firebasestorage.app',
    iosBundleId: 'com.example.fpRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATkmYhJbKldDd93-CctvMDVsr0K26SkjM',
    appId: '1:845713431117:ios:defb6f8fd78883fed49a04',
    messagingSenderId: '845713431117',
    projectId: 'fp-ppb-recipe',
    storageBucket: 'fp-ppb-recipe.firebasestorage.app',
    iosBundleId: 'com.example.fpRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTjRCgSBD2AdmEsvUmSyKJ8SOmKG2ztqI',
    appId: '1:845713431117:web:609caa99347d8db8d49a04',
    messagingSenderId: '845713431117',
    projectId: 'fp-ppb-recipe',
    authDomain: 'fp-ppb-recipe.firebaseapp.com',
    storageBucket: 'fp-ppb-recipe.firebasestorage.app',
    measurementId: 'G-HH2S01FJTD',
  );
}
